### ISSUE TITLE
Decrypting with wrong password

### ISSUE THREAD

**Issue by rafieissam** [jlinoff/lock_files#8]
Hello, I installed this repo and I was checking it out to use it within a project. However, it turns out after I encrypt something and the time for decryption comes, the decryption never fails. No matter what password you choose it always decrypts. Please try this out and inform me if I might be doing something wrong or if your code needs editing.

**Comment by jlinoff** [comment]
Thanks for letting me know.

What version of python are you using?

Also, could you send me the output of `pip freeze` so i can see which versions of packages you are using?

**Comment by rafieissam** [comment]
Python 3.8.0

I just started on a fresh environment, these are my packages:

cffi==1.14.0
cryptography==2.9.2
pycparser==2.20
six==1.14.0
virtualenv==16.7.7

**Comment by jlinoff** [comment]
Perfect, thank you. I will take a look at it and respond in the next few days.

**Comment by rafieissam** [comment]
I have to apologize. I got distracted while testing. What happened was the file i was decrypting with a wrong password turned back into the original file. However, the data was corrupted, so it wasn't really decrypting with a wrong password. Sorry, I had a lot on my mind today.

**Comment by jlinoff** [comment]
No problem. I am glad that it is working for you and really I appreciate you following up to let me know.
